export const ActionType = {
  OPEN_CLOSE_MODAL: "OPEN_CLOSE_MODAL",
  OPEN_CLOSE_SHOW_MOVIE_DETAIL: "OPEN_CLOSE_SHOW_MOVIE_DETAIL",
  SET_MOTAL: "SET_MOTAL",
  MOVIE_DETAIL: "MOVIE_DETAIL",
  MODAL_TYPE: "MODAL_TYPE",
  SET_MOVIES: "SET_MOVIES",
  SELECTED_MOVIE: "SELECTED_MOVIE",
};
